package com.ctsi.zz.domain;

import com.ctsi.ssdc.criteria.IntegerCriteria;
import com.ctsi.ssdc.criteria.StringCriteria;
import com.ctsi.ssdc.criteria.ZonedDateTimeCriteria;
import com.ctsi.ssdc.example.BaseExample;
import io.swagger.annotations.ApiParam;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang3.StringUtils;

/**
 * @author ctsi-biyi-generator
*/
public class CandidatesExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private static final String LIKE_FORMAT = "%%%s%%";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.phone
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.id
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.name
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.email
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.type
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.position
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.years
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria years;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.age
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private IntegerCriteria age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.education
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.politic
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria politic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.universities
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria universities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.major
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.status
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.entryTime
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private ZonedDateTimeCriteria entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.salary
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.url
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private StringCriteria url;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public CandidatesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setPhone(StringCriteria phone) {
        this. phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildPhoneCriteria(Criteria criteria) {
        if (this.getPhone() == null) {
            return;
        }
        if (this.getPhone().getEquals() != null) {
            criteria.andPhoneEqualTo(this.getPhone().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getPhone().getContains())) {
                criteria.andPhoneLike(String.format(LIKE_FORMAT, this.getPhone().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setId(StringCriteria id) {
        this. id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildIdCriteria(Criteria criteria) {
        if (this.getId() == null) {
            return;
        }
        if (this.getId().getEquals() != null) {
            criteria.andIdEqualTo(this.getId().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getId().getContains())) {
                criteria.andIdLike(String.format(LIKE_FORMAT, this.getId().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setName(StringCriteria name) {
        this. name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildNameCriteria(Criteria criteria) {
        if (this.getName() == null) {
            return;
        }
        if (this.getName().getEquals() != null) {
            criteria.andNameEqualTo(this.getName().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getName().getContains())) {
                criteria.andNameLike(String.format(LIKE_FORMAT, this.getName().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setEmail(StringCriteria email) {
        this. email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildEmailCriteria(Criteria criteria) {
        if (this.getEmail() == null) {
            return;
        }
        if (this.getEmail().getEquals() != null) {
            criteria.andEmailEqualTo(this.getEmail().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getEmail().getContains())) {
                criteria.andEmailLike(String.format(LIKE_FORMAT, this.getEmail().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setType(StringCriteria type) {
        this. type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildTypeCriteria(Criteria criteria) {
        if (this.getType() == null) {
            return;
        }
        if (this.getType().getEquals() != null) {
            criteria.andTypeEqualTo(this.getType().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getType().getContains())) {
                criteria.andTypeLike(String.format(LIKE_FORMAT, this.getType().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setPosition(StringCriteria position) {
        this. position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildPositionCriteria(Criteria criteria) {
        if (this.getPosition() == null) {
            return;
        }
        if (this.getPosition().getEquals() != null) {
            criteria.andPositionEqualTo(this.getPosition().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getPosition().getContains())) {
                criteria.andPositionLike(String.format(LIKE_FORMAT, this.getPosition().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setYears(StringCriteria years) {
        this. years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildYearsCriteria(Criteria criteria) {
        if (this.getYears() == null) {
            return;
        }
        if (this.getYears().getEquals() != null) {
            criteria.andYearsEqualTo(this.getYears().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getYears().getContains())) {
                criteria.andYearsLike(String.format(LIKE_FORMAT, this.getYears().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public IntegerCriteria getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setAge(IntegerCriteria age) {
        this. age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildAgeCriteria(Criteria criteria) {
        if (this.getAge() == null) {
            return;
        }
        if (this.getAge().getEquals() != null) {
            criteria.andAgeEqualTo(this.getAge().getEquals());
        } else {
            if (this.getAge().getGreaterOrEqualThan() != null) {
                criteria.andAgeGreaterThanOrEqualTo(this.getAge().getGreaterOrEqualThan());
            }
            if (this.getAge().getLessOrEqualThan() != null) {
                criteria.andAgeLessThanOrEqualTo(this.getAge().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setEducation(StringCriteria education) {
        this. education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildEducationCriteria(Criteria criteria) {
        if (this.getEducation() == null) {
            return;
        }
        if (this.getEducation().getEquals() != null) {
            criteria.andEducationEqualTo(this.getEducation().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getEducation().getContains())) {
                criteria.andEducationLike(String.format(LIKE_FORMAT, this.getEducation().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getPolitic() {
        return politic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setPolitic(StringCriteria politic) {
        this. politic = politic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildPoliticCriteria(Criteria criteria) {
        if (this.getPolitic() == null) {
            return;
        }
        if (this.getPolitic().getEquals() != null) {
            criteria.andPoliticEqualTo(this.getPolitic().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getPolitic().getContains())) {
                criteria.andPoliticLike(String.format(LIKE_FORMAT, this.getPolitic().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getUniversities() {
        return universities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setUniversities(StringCriteria universities) {
        this. universities = universities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildUniversitiesCriteria(Criteria criteria) {
        if (this.getUniversities() == null) {
            return;
        }
        if (this.getUniversities().getEquals() != null) {
            criteria.andUniversitiesEqualTo(this.getUniversities().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getUniversities().getContains())) {
                criteria.andUniversitiesLike(String.format(LIKE_FORMAT, this.getUniversities().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setMajor(StringCriteria major) {
        this. major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildMajorCriteria(Criteria criteria) {
        if (this.getMajor() == null) {
            return;
        }
        if (this.getMajor().getEquals() != null) {
            criteria.andMajorEqualTo(this.getMajor().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getMajor().getContains())) {
                criteria.andMajorLike(String.format(LIKE_FORMAT, this.getMajor().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setStatus(StringCriteria status) {
        this. status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildStatusCriteria(Criteria criteria) {
        if (this.getStatus() == null) {
            return;
        }
        if (this.getStatus().getEquals() != null) {
            criteria.andStatusEqualTo(this.getStatus().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getStatus().getContains())) {
                criteria.andStatusLike(String.format(LIKE_FORMAT, this.getStatus().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public ZonedDateTimeCriteria getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setEntrytime(ZonedDateTimeCriteria entrytime) {
        this. entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildEntrytimeCriteria(Criteria criteria) {
        if (this.getEntrytime() == null) {
            return;
        }
        if (this.getEntrytime().getEquals() != null) {
            criteria.andEntrytimeEqualTo(this.getEntrytime().getEquals());
        } else {
            if (this.getEntrytime().getGreaterOrEqualThan() != null) {
                criteria.andEntrytimeGreaterThanOrEqualTo(this.getEntrytime().getGreaterOrEqualThan());
            }
            if (this.getEntrytime().getLessOrEqualThan() != null) {
                criteria.andEntrytimeLessThanOrEqualTo(this.getEntrytime().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setSalary(StringCriteria salary) {
        this. salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildSalaryCriteria(Criteria criteria) {
        if (this.getSalary() == null) {
            return;
        }
        if (this.getSalary().getEquals() != null) {
            criteria.andSalaryEqualTo(this.getSalary().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getSalary().getContains())) {
                criteria.andSalaryLike(String.format(LIKE_FORMAT, this.getSalary().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public StringCriteria getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setUrl(StringCriteria url) {
        this. url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private void buildUrlCriteria(Criteria criteria) {
        if (this.getUrl() == null) {
            return;
        }
        if (this.getUrl().getEquals() != null) {
            criteria.andUrlEqualTo(this.getUrl().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getUrl().getContains())) {
                criteria.andUrlLike(String.format(LIKE_FORMAT, this.getUrl().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public Object buildCriteria() {
        Criteria criteria = this.createCriteria();
        this.buildPhoneCriteria(criteria);
        this.buildIdCriteria(criteria);
        this.buildNameCriteria(criteria);
        this.buildEmailCriteria(criteria);
        this.buildTypeCriteria(criteria);
        this.buildPositionCriteria(criteria);
        this.buildYearsCriteria(criteria);
        this.buildAgeCriteria(criteria);
        this.buildEducationCriteria(criteria);
        this.buildPoliticCriteria(criteria);
        this.buildUniversitiesCriteria(criteria);
        this.buildMajorCriteria(criteria);
        this.buildStatusCriteria(criteria);
        this.buildEntrytimeCriteria(criteria);
        this.buildSalaryCriteria(criteria);
        this.buildUrlCriteria(criteria);
        return criteria;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("position like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("position not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andYearsIsNull() {
            addCriterion("years is null");
            return (Criteria) this;
        }

        public Criteria andYearsIsNotNull() {
            addCriterion("years is not null");
            return (Criteria) this;
        }

        public Criteria andYearsEqualTo(String value) {
            addCriterion("years =", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsNotEqualTo(String value) {
            addCriterion("years <>", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsGreaterThan(String value) {
            addCriterion("years >", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsGreaterThanOrEqualTo(String value) {
            addCriterion("years >=", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsLessThan(String value) {
            addCriterion("years <", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsLessThanOrEqualTo(String value) {
            addCriterion("years <=", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsLike(String value) {
            addCriterion("years like", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsNotLike(String value) {
            addCriterion("years not like", value, "years");
            return (Criteria) this;
        }

        public Criteria andYearsIn(List<String> values) {
            addCriterion("years in", values, "years");
            return (Criteria) this;
        }

        public Criteria andYearsNotIn(List<String> values) {
            addCriterion("years not in", values, "years");
            return (Criteria) this;
        }

        public Criteria andYearsBetween(String value1, String value2) {
            addCriterion("years between", value1, value2, "years");
            return (Criteria) this;
        }

        public Criteria andYearsNotBetween(String value1, String value2) {
            addCriterion("years not between", value1, value2, "years");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andEducationIsNull() {
            addCriterion("education is null");
            return (Criteria) this;
        }

        public Criteria andEducationIsNotNull() {
            addCriterion("education is not null");
            return (Criteria) this;
        }

        public Criteria andEducationEqualTo(String value) {
            addCriterion("education =", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotEqualTo(String value) {
            addCriterion("education <>", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationGreaterThan(String value) {
            addCriterion("education >", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationGreaterThanOrEqualTo(String value) {
            addCriterion("education >=", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLessThan(String value) {
            addCriterion("education <", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLessThanOrEqualTo(String value) {
            addCriterion("education <=", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLike(String value) {
            addCriterion("education like", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotLike(String value) {
            addCriterion("education not like", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationIn(List<String> values) {
            addCriterion("education in", values, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotIn(List<String> values) {
            addCriterion("education not in", values, "education");
            return (Criteria) this;
        }

        public Criteria andEducationBetween(String value1, String value2) {
            addCriterion("education between", value1, value2, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotBetween(String value1, String value2) {
            addCriterion("education not between", value1, value2, "education");
            return (Criteria) this;
        }

        public Criteria andPoliticIsNull() {
            addCriterion("politic is null");
            return (Criteria) this;
        }

        public Criteria andPoliticIsNotNull() {
            addCriterion("politic is not null");
            return (Criteria) this;
        }

        public Criteria andPoliticEqualTo(String value) {
            addCriterion("politic =", value, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticNotEqualTo(String value) {
            addCriterion("politic <>", value, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticGreaterThan(String value) {
            addCriterion("politic >", value, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticGreaterThanOrEqualTo(String value) {
            addCriterion("politic >=", value, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticLessThan(String value) {
            addCriterion("politic <", value, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticLessThanOrEqualTo(String value) {
            addCriterion("politic <=", value, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticLike(String value) {
            addCriterion("politic like", value, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticNotLike(String value) {
            addCriterion("politic not like", value, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticIn(List<String> values) {
            addCriterion("politic in", values, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticNotIn(List<String> values) {
            addCriterion("politic not in", values, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticBetween(String value1, String value2) {
            addCriterion("politic between", value1, value2, "politic");
            return (Criteria) this;
        }

        public Criteria andPoliticNotBetween(String value1, String value2) {
            addCriterion("politic not between", value1, value2, "politic");
            return (Criteria) this;
        }

        public Criteria andUniversitiesIsNull() {
            addCriterion("universities is null");
            return (Criteria) this;
        }

        public Criteria andUniversitiesIsNotNull() {
            addCriterion("universities is not null");
            return (Criteria) this;
        }

        public Criteria andUniversitiesEqualTo(String value) {
            addCriterion("universities =", value, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesNotEqualTo(String value) {
            addCriterion("universities <>", value, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesGreaterThan(String value) {
            addCriterion("universities >", value, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesGreaterThanOrEqualTo(String value) {
            addCriterion("universities >=", value, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesLessThan(String value) {
            addCriterion("universities <", value, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesLessThanOrEqualTo(String value) {
            addCriterion("universities <=", value, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesLike(String value) {
            addCriterion("universities like", value, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesNotLike(String value) {
            addCriterion("universities not like", value, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesIn(List<String> values) {
            addCriterion("universities in", values, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesNotIn(List<String> values) {
            addCriterion("universities not in", values, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesBetween(String value1, String value2) {
            addCriterion("universities between", value1, value2, "universities");
            return (Criteria) this;
        }

        public Criteria andUniversitiesNotBetween(String value1, String value2) {
            addCriterion("universities not between", value1, value2, "universities");
            return (Criteria) this;
        }

        public Criteria andMajorIsNull() {
            addCriterion("major is null");
            return (Criteria) this;
        }

        public Criteria andMajorIsNotNull() {
            addCriterion("major is not null");
            return (Criteria) this;
        }

        public Criteria andMajorEqualTo(String value) {
            addCriterion("major =", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotEqualTo(String value) {
            addCriterion("major <>", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThan(String value) {
            addCriterion("major >", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThanOrEqualTo(String value) {
            addCriterion("major >=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThan(String value) {
            addCriterion("major <", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThanOrEqualTo(String value) {
            addCriterion("major <=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLike(String value) {
            addCriterion("major like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotLike(String value) {
            addCriterion("major not like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorIn(List<String> values) {
            addCriterion("major in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotIn(List<String> values) {
            addCriterion("major not in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorBetween(String value1, String value2) {
            addCriterion("major between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotBetween(String value1, String value2) {
            addCriterion("major not between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNull() {
            addCriterion("entryTime is null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNotNull() {
            addCriterion("entryTime is not null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeEqualTo(ZonedDateTime value) {
            addCriterion("entryTime =", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotEqualTo(ZonedDateTime value) {
            addCriterion("entryTime <>", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThan(ZonedDateTime value) {
            addCriterion("entryTime >", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThanOrEqualTo(ZonedDateTime value) {
            addCriterion("entryTime >=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThan(ZonedDateTime value) {
            addCriterion("entryTime <", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThanOrEqualTo(ZonedDateTime value) {
            addCriterion("entryTime <=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIn(List<ZonedDateTime> values) {
            addCriterion("entryTime in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotIn(List<ZonedDateTime> values) {
            addCriterion("entryTime not in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeBetween(ZonedDateTime value1, ZonedDateTime value2) {
            addCriterion("entryTime between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotBetween(ZonedDateTime value1, ZonedDateTime value2) {
            addCriterion("entryTime not between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andSalaryIsNull() {
            addCriterion("salary is null");
            return (Criteria) this;
        }

        public Criteria andSalaryIsNotNull() {
            addCriterion("salary is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryEqualTo(String value) {
            addCriterion("salary =", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotEqualTo(String value) {
            addCriterion("salary <>", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryGreaterThan(String value) {
            addCriterion("salary >", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryGreaterThanOrEqualTo(String value) {
            addCriterion("salary >=", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLessThan(String value) {
            addCriterion("salary <", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLessThanOrEqualTo(String value) {
            addCriterion("salary <=", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLike(String value) {
            addCriterion("salary like", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotLike(String value) {
            addCriterion("salary not like", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryIn(List<String> values) {
            addCriterion("salary in", values, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotIn(List<String> values) {
            addCriterion("salary not in", values, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryBetween(String value1, String value2) {
            addCriterion("salary between", value1, value2, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotBetween(String value1, String value2) {
            addCriterion("salary not between", value1, value2, "salary");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table candidates
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 27 14:46:33 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public static class Criterion {
        @ApiParam(hidden=true)
        private String condition;

        @ApiParam(hidden=true)
        private Object value;

        @ApiParam(hidden=true)
        private Object secondValue;

        @ApiParam(hidden=true)
        private boolean noValue;

        @ApiParam(hidden=true)
        private boolean singleValue;

        @ApiParam(hidden=true)
        private boolean betweenValue;

        @ApiParam(hidden=true)
        private boolean listValue;

        @ApiParam(hidden=true)
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}