package com.ctsi.zz.domain;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.time.ZonedDateTime;

/**
 * @author ctsi-biyi-generator
*/
public class Candidates implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.phone
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */

    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.id
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    @ApiModelProperty(value = "id")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.name
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    @ApiModelProperty(value = "姓名")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.email
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    @ApiModelProperty(value = "邮箱")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.type
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    @ApiModelProperty(value = "类型")
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.position
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.years
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String years;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.age
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.education
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.politic
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String politic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.universities
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String universities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.major
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.status
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.entryTime
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    @ApiModelProperty(value = "创建时间")
    private ZonedDateTime entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.salary
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidates.url
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.phone
     *
     * @return the value of candidates.phone
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.phone
     *
     * @param phone the value for candidates.phone
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.id
     *
     * @return the value of candidates.id
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.id
     *
     * @param id the value for candidates.id
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.name
     *
     * @return the value of candidates.name
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.name
     *
     * @param name the value for candidates.name
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.email
     *
     * @return the value of candidates.email
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.email
     *
     * @param email the value for candidates.email
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.type
     *
     * @return the value of candidates.type
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.type
     *
     * @param type the value for candidates.type
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.position
     *
     * @return the value of candidates.position
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.position
     *
     * @param position the value for candidates.position
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.years
     *
     * @return the value of candidates.years
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.years
     *
     * @param years the value for candidates.years
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setYears(String years) {
        this.years = years == null ? null : years.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.age
     *
     * @return the value of candidates.age
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.age
     *
     * @param age the value for candidates.age
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.education
     *
     * @return the value of candidates.education
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.education
     *
     * @param education the value for candidates.education
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.politic
     *
     * @return the value of candidates.politic
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getPolitic() {
        return politic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.politic
     *
     * @param politic the value for candidates.politic
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setPolitic(String politic) {
        this.politic = politic == null ? null : politic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.universities
     *
     * @return the value of candidates.universities
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getUniversities() {
        return universities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.universities
     *
     * @param universities the value for candidates.universities
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setUniversities(String universities) {
        this.universities = universities == null ? null : universities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.major
     *
     * @return the value of candidates.major
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.major
     *
     * @param major the value for candidates.major
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.status
     *
     * @return the value of candidates.status
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.status
     *
     * @param status the value for candidates.status
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.entryTime
     *
     * @return the value of candidates.entryTime
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public ZonedDateTime getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.entryTime
     *
     * @param entrytime the value for candidates.entryTime
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setEntrytime(ZonedDateTime entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.salary
     *
     * @return the value of candidates.salary
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.salary
     *
     * @param salary the value for candidates.salary
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setSalary(String salary) {
        this.salary = salary == null ? null : salary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidates.url
     *
     * @return the value of candidates.url
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidates.url
     *
     * @param url the value for candidates.url
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Candidates other = (Candidates) that;
        return (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getYears() == null ? other.getYears() == null : this.getYears().equals(other.getYears()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getEducation() == null ? other.getEducation() == null : this.getEducation().equals(other.getEducation()))
            && (this.getPolitic() == null ? other.getPolitic() == null : this.getPolitic().equals(other.getPolitic()))
            && (this.getUniversities() == null ? other.getUniversities() == null : this.getUniversities().equals(other.getUniversities()))
            && (this.getMajor() == null ? other.getMajor() == null : this.getMajor().equals(other.getMajor()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getEntrytime() == null ? other.getEntrytime() == null : this.getEntrytime().equals(other.getEntrytime()))
            && (this.getSalary() == null ? other.getSalary() == null : this.getSalary().equals(other.getSalary()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getYears() == null) ? 0 : getYears().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getEducation() == null) ? 0 : getEducation().hashCode());
        result = prime * result + ((getPolitic() == null) ? 0 : getPolitic().hashCode());
        result = prime * result + ((getUniversities() == null) ? 0 : getUniversities().hashCode());
        result = prime * result + ((getMajor() == null) ? 0 : getMajor().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getEntrytime() == null) ? 0 : getEntrytime().hashCode());
        result = prime * result + ((getSalary() == null) ? 0 : getSalary().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        return result;
    }
}