# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: biyi
    profiles:
         active: dev,swagger
    jackson:
        serialization.write_dates_as_timestamps: false   
    mvc:
        favicon:
            enabled: false      
                  
management:
    endpoints:
        web:
            #监控接口
            exposure:
                include: "info,health,prometheus"

ctsi:
    swagger:
        default-include-pattern: /api/.*
        title: ctsi Manage API
        description: ctsi API documentation
        version: 0.0.1
        terms-of-service-url: http://www.ctsi.com.cn/
        contact-name: 赵子龙
        contact-url: http://zl0810.com
        contact-email: zl_java@163.com
        license:
        license-url:

    jwtfilter:
        enable: false
