package com.ctsi.zz.repository;

import com.ctsi.zz.domain.Candidates;
import com.ctsi.zz.domain.CandidatesExample.Criteria;
import com.ctsi.zz.domain.CandidatesExample.Criterion;
import com.ctsi.zz.domain.CandidatesExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

/**
 * @author ctsi-biyi-generator
*/
public class CandidatesSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String countByExample(CandidatesExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("candidates");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String deleteByExample(CandidatesExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("candidates");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String insertSelective(Candidates record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("candidates");
        
        if (record.getPhone() != null) {
            sql.VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=VARCHAR}");
        }
        
        if (record.getPosition() != null) {
            sql.VALUES("position", "#{position,jdbcType=VARCHAR}");
        }
        
        if (record.getYears() != null) {
            sql.VALUES("years", "#{years,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.VALUES("age", "#{age,jdbcType=INTEGER}");
        }
        
        if (record.getEducation() != null) {
            sql.VALUES("education", "#{education,jdbcType=VARCHAR}");
        }
        
        if (record.getPolitic() != null) {
            sql.VALUES("politic", "#{politic,jdbcType=VARCHAR}");
        }
        
        if (record.getUniversities() != null) {
            sql.VALUES("universities", "#{universities,jdbcType=VARCHAR}");
        }
        
        if (record.getMajor() != null) {
            sql.VALUES("major", "#{major,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getEntrytime() != null) {
            sql.VALUES("entryTime", "#{entrytime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSalary() != null) {
            sql.VALUES("salary", "#{salary,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String selectByExample(CandidatesExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("phone");
        } else {
            sql.SELECT("phone");
        }
        sql.SELECT("id");
        sql.SELECT("name");
        sql.SELECT("email");
        sql.SELECT("type");
        sql.SELECT("position");
        sql.SELECT("years");
        sql.SELECT("age");
        sql.SELECT("education");
        sql.SELECT("politic");
        sql.SELECT("universities");
        sql.SELECT("major");
        sql.SELECT("status");
        sql.SELECT("entryTime");
        sql.SELECT("salary");
        sql.SELECT("url");
        sql.FROM("candidates");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Candidates record = (Candidates) parameter.get("record");
        CandidatesExample example = (CandidatesExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("candidates");
        
        if (record.getPhone() != null) {
            sql.SET("phone = #{record.phone,jdbcType=VARCHAR}");
        }
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("email = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{record.type,jdbcType=VARCHAR}");
        }
        
        if (record.getPosition() != null) {
            sql.SET("position = #{record.position,jdbcType=VARCHAR}");
        }
        
        if (record.getYears() != null) {
            sql.SET("years = #{record.years,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.SET("age = #{record.age,jdbcType=INTEGER}");
        }
        
        if (record.getEducation() != null) {
            sql.SET("education = #{record.education,jdbcType=VARCHAR}");
        }
        
        if (record.getPolitic() != null) {
            sql.SET("politic = #{record.politic,jdbcType=VARCHAR}");
        }
        
        if (record.getUniversities() != null) {
            sql.SET("universities = #{record.universities,jdbcType=VARCHAR}");
        }
        
        if (record.getMajor() != null) {
            sql.SET("major = #{record.major,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        }
        
        if (record.getEntrytime() != null) {
            sql.SET("entryTime = #{record.entrytime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSalary() != null) {
            sql.SET("salary = #{record.salary,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{record.url,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("candidates");
        
        sql.SET("phone = #{record.phone,jdbcType=VARCHAR}");
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        sql.SET("email = #{record.email,jdbcType=VARCHAR}");
        sql.SET("type = #{record.type,jdbcType=VARCHAR}");
        sql.SET("position = #{record.position,jdbcType=VARCHAR}");
        sql.SET("years = #{record.years,jdbcType=VARCHAR}");
        sql.SET("age = #{record.age,jdbcType=INTEGER}");
        sql.SET("education = #{record.education,jdbcType=VARCHAR}");
        sql.SET("politic = #{record.politic,jdbcType=VARCHAR}");
        sql.SET("universities = #{record.universities,jdbcType=VARCHAR}");
        sql.SET("major = #{record.major,jdbcType=VARCHAR}");
        sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        sql.SET("entryTime = #{record.entrytime,jdbcType=TIMESTAMP}");
        sql.SET("salary = #{record.salary,jdbcType=VARCHAR}");
        sql.SET("url = #{record.url,jdbcType=VARCHAR}");
        
        CandidatesExample example = (CandidatesExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    public String updateByPrimaryKeySelective(Candidates record) {
        SQL sql = new SQL();
        sql.UPDATE("candidates");
        
        if (record.getId() != null) {
            sql.SET("id = #{id,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=VARCHAR}");
        }
        
        if (record.getPosition() != null) {
            sql.SET("position = #{position,jdbcType=VARCHAR}");
        }
        
        if (record.getYears() != null) {
            sql.SET("years = #{years,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.SET("age = #{age,jdbcType=INTEGER}");
        }
        
        if (record.getEducation() != null) {
            sql.SET("education = #{education,jdbcType=VARCHAR}");
        }
        
        if (record.getPolitic() != null) {
            sql.SET("politic = #{politic,jdbcType=VARCHAR}");
        }
        
        if (record.getUniversities() != null) {
            sql.SET("universities = #{universities,jdbcType=VARCHAR}");
        }
        
        if (record.getMajor() != null) {
            sql.SET("major = #{major,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getEntrytime() != null) {
            sql.SET("entryTime = #{entrytime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSalary() != null) {
            sql.SET("salary = #{salary,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("phone = #{phone,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidates
     *
     * @mbg.generated Fri Nov 27 14:46:33 CST 2020
     */
    protected void applyWhere(SQL sql, CandidatesExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}